/** Catálogo de regalos — Baby Shower de Mateo */
window.WISHLIST_ITEMS = [
  { id: "mochila-portabebe", name: "Mochila portabebé", category: "Paseo y cambio", image: "images/wishlist/mochila-portabebe.jpg", url: "https://listado.mercadolibre.com.ar/mochila-portabebe" },
  { id: "bolso-maternal", name: "Bolso maternal grande", category: "Paseo y cambio", image: "images/wishlist/bolso-maternal.jpg", url: "https://listado.mercadolibre.com.ar/bolso-maternal-bebe" },
  { id: "cambiador-portatil", name: "Cambiadores portátiles", category: "Paseo y cambio", image: "images/wishlist/cambiador-portatil.jpg", url: "https://listado.mercadolibre.com.ar/cambiador-portatil-bebe" },
  { id: "cambiador-rigido", name: "Cambiador rígido", category: "Paseo y cambio", image: "images/wishlist/cambiador-rigido.jpg", url: "https://listado.mercadolibre.com.ar/cambiador-rigido-bebe" },

  { id: "banera", name: "Bañera con termómetro y reductor", category: "Baño", image: "images/wishlist/banera.jpg", url: "https://listado.mercadolibre.com.ar/banera-bebe-termometro" },
  { id: "batita-bano", name: "Batita de baño con capucha", category: "Baño", image: "images/wishlist/batita-bano.jpg", url: "https://www.mercadolibre.com.ar/toalla-bata-con-capucha-ninos-apego-manta-de-bano/up/MLAU3318728938" },
  { id: "mantas", name: "Mantas de algodón / recibidores", category: "Baño", image: "images/wishlist/mantas.jpg", url: "https://articulo.mercadolibre.com.ar/MLA-2050098992-manta-bebe-recibidora-beba-ajuar-nacimiento-algodon-unisex-_JM" },

  { id: "luz-nocturna", name: "Luz nocturna", category: "Descanso", image: "images/wishlist/luz-nocturna.jpg", url: "https://listado.mercadolibre.com.ar/luz-nocturna-bebe" },
  { id: "ruido-blanco", name: "Máquina de ruido blanco", category: "Descanso", image: "images/wishlist/ruido-blanco.jpg", url: "https://www.cetrogar.com.ar/maquina-de-ruido-blanco-dehuka-con-luz-nocturna-para-bebes-y-ni%C3%B1os-baby2896/p?idsku=4125" },

  { id: "sacaleche", name: "Sacaleche", category: "Lactancia", image: "images/wishlist/sacaleche.jpg", url: "https://listado.mercadolibre.com.ar/sacaleche-electrico" },
  { id: "mamadera-rn", name: "Mamadera para recién nacido", category: "Lactancia", image: "images/wishlist/mamadera-rn.jpg", url: "https://www.babelito.com/producto/set-recien-nacido-2/" },
  { id: "mamadera-grande", name: "Mamadera grande", category: "Lactancia", image: "images/wishlist/mamadera-grande.jpg", url: "https://www.fravega.com/p/mamadera-avent-natural-response-scy903-01-260-ml-680690/" },
  { id: "cepillo-mamaderas", name: "Cepillo para limpiar mamaderas", category: "Lactancia", image: "images/wishlist/cepillo-mamaderas.jpg", url: "https://www.farmaciastkl.com/cepillo-limpia-mamadera/p" },
  { id: "esterilizador", name: "Esterilizador", category: "Lactancia", image: "images/wishlist/esterilizador.jpg", url: "https://www.mercadolibre.com.ar/esterilizador-doble-mamaderas-mawe-by-gadnic-calentador-multifuncion-control-temperatura/p/MLA48597143" },
  { id: "almohadon-amamantar", name: "Almohadón para amamantar", category: "Lactancia", image: "images/wishlist/almohadon-amamantar.jpg", url: "https://articulo.mercadolibre.com.ar/MLA-901836250-almohadon-para-amamantar-con-funda-con-cierre-_JM" },

  { id: "jabon-ropa", name: "Jabón para lavar la ropa del bebé", category: "Higiene", image: "images/wishlist/jabon-ropa.jpg", url: "https://www.mercadolibre.com.ar/jabon-liquido-woolite-bebe-matic-repuesto-900ml/p/MLA17361029" },
  { id: "oleo", name: "Óleo sin perfume", category: "Higiene", image: "images/wishlist/oleo.jpg", url: "https://www.mercadolibre.com.ar/oleo-calcareo-estrella-baby-sin-fragancia-x-950-ml-con-extracto-de-algodon-hipoalergenico/p/MLA15993170" },
  { id: "algodon", name: "Algodón precortado", category: "Higiene", image: "images/wishlist/algodon.jpg", url: "https://www.mercadolibre.com.ar/6-pack-algodon-precortado-hidrofilo-estrella-baby-x-100grs/up/MLAU221228687" },
  { id: "jabon-liquido", name: "Jabón líquido de pies a cabeza", category: "Higiene", image: "images/wishlist/jabon-liquido.jpg", url: "https://listado.mercadolibre.com.ar/jabon-liquido-bebe" },
  { id: "kit-higiene", name: "Kit de higiene y cuidado de la piel", category: "Higiene", image: "images/wishlist/kit-higiene.jpg", url: "https://www.mercadolibre.com.ar/set-bebe-completo13-accesorios-higiene-y-cuidado-bebe-0/up/MLAU3441071108" },
  { id: "pomada", name: "Pomada para paspaduras", category: "Higiene", image: "images/wishlist/pomada.jpg", url: "https://www.mercadolibre.com.ar/kit-crema-hipoglos-cuidado-diario-30gr-x2/up/MLAU236563717" },
  { id: "toallitas", name: "Toallitas húmedas sin perfume y sin alcohol", category: "Higiene", image: "images/wishlist/toallitas.jpg", url: "https://www.mercadolibre.com.ar/toallitas-humedas-estrella-baby-cuidado-diario-x-50-unidades/p/MLA66590234" },
  { id: "kit-aseo", name: "Kit de aseo", category: "Higiene", image: "images/wishlist/kit-aseo.jpg", url: "https://articulo.mercadolibre.com.ar/MLA-1549263539-set-higiene-bebe-kit-aseo-recien-nacido-baby-care-kit-10-pzs-_JM" },
  { id: "sacamocos", name: "Sacamocos", category: "Higiene", image: "images/wishlist/sacamocos.jpg", url: "https://www.mercadolibre.com.ar/aspirador-nasal-electrico-portatil-para-bebes-usb-recargable/up/MLAU3403744283" },
  { id: "termometro", name: "Termómetro", category: "Higiene", image: "images/wishlist/termometro.jpg", url: "https://www.mercadolibre.com.ar/citizen-cta301c-termometro-digital-silfab-oral-rectal-axilar/p/MLA35944743" },

  { id: "panales-rn", name: "Pañales recién nacido", category: "Pañales", image: "images/wishlist/panales-rn.jpg", url: "https://www.mercadolibre.com.ar/panales-pampers-deluxe-protection-recien-nacido-talle-rn-36-un/p/MLA28051654" },
  { id: "panales-p", name: "Pañales talle P", category: "Pañales", image: "images/wishlist/panales-p.jpg", url: "https://www.mercadolibre.com.ar/panales-baby-dry-hipoalergenico-talle-p-x-36-un/p/MLA67987907" },
  { id: "panales-m", name: "Pañales talle M", category: "Pañales", image: "images/wishlist/panales-m.jpg", url: "https://www.mercadolibre.com.ar/pampers-baby-dry-hipoalergenico-panales-desechables-talle-m-52-unidades/p/MLA25868818" },

  { id: "ajuares", name: "Ajuares", category: "Ropa", image: "images/wishlist/ajuares.jpg", url: "https://www.mercadolibre.com.ar/ajuar-bebe-conjunto-recien-nacido-7-piezas-caja-regalo/up/MLAU4179666059" },
  { id: "body-corta", name: "Bodies manga corta", category: "Ropa", image: "images/wishlist/body-corta.jpg", url: "https://www.mercadolibre.com.ar/pack-x4-body-manga-corta-liso-100-algodon--recien-nacido/up/MLAU3661392031" },
  { id: "body-larga", name: "Bodies manga larga", category: "Ropa", image: "images/wishlist/body-larga.jpg", url: "https://www.mercadolibre.com.ar/body-pachibebes-100-algodon-manga-larga-color-verde-talle-1-3-m/p/MLA64217118" },
  { id: "ranitas", name: "Ranitas o pantaloncitos con pie", category: "Ropa", image: "images/wishlist/ranitas.jpg", url: "https://www.mercadolibre.com.ar/ranitas-algodon-100--excelente-calidad/up/MLAU3937332026" },
  { id: "camiseta-short", name: "Camisetas manga corta y shortcitos", category: "Ropa", image: "images/wishlist/camiseta-short.jpg", url: "https://articulo.mercadolibre.com.ar/MLA-876806171-conjunto-bebe-remera-y-short-algodon-con-dibujo-_JM" },
  { id: "enterito-pijama", name: "Enteritos pijama largo con cierre", category: "Ropa", image: "images/wishlist/enterito-pijama.jpg", url: "https://www.mercadolibre.com.ar/enteritos-recien-nacidos-varios-colores-100-algodon-oferta/up/MLAU4256046575" },
  { id: "enterito-tirita", name: "Enteritos de tirita", category: "Ropa", image: "images/wishlist/enterito-tirita.jpg", url: "https://articulo.mercadolibre.com.ar/MLA-1843456359-enterito-bodys-para-bebe-con-gorro-algodon-recien-nacido-_JM" },
  { id: "medias", name: "Pares de medias", category: "Ropa", image: "images/wishlist/medias.jpg", url: "https://www.mercadolibre.com.ar/medias-bebe-algodon-recien-nacido-hasta-6-meses-chufi-bebes/up/MLAU3203879073" },
  { id: "gorritos", name: "Gorritos de algodón fino", category: "Ropa", image: "images/wishlist/gorritos.jpg", url: "https://www.mercadolibre.com.ar/gorrito-tejido-bebe-argentina/up/MLAU3871723310" },
  { id: "mitones", name: "Pares de mitones", category: "Ropa", image: "images/wishlist/mitones.jpg", url: "https://articulo.mercadolibre.com.ar/MLA-1375523979-mitones-de-algodon-pima-para-recien-nacidos-talle-unico-_JM" },
  { id: "babitas", name: "Babitas", category: "Ropa", image: "images/wishlist/babitas.jpg", url: "https://www.mercadolibre.com.ar/pack-x-6-babitas-bebe-con-toalla-estampa-surtida-color-unisex/p/MLA75290400" },
  { id: "baberos", name: "Baberos", category: "Ropa", image: "images/wishlist/baberos.jpg", url: "https://www.coppel.com.ar/7-baberos-con-tematica-de-osos-en-tonos-beiges-y-v-5110280/p" },

  { id: "corpino", name: "Corpiños para amamantar", category: "Para mamá", image: "images/wishlist/corpino.jpg", url: "https://www.victorialingerie.com.ar/productos/corpino-maternal-algodon-3045/" },
  { id: "pantuflas", name: "Pantuflas", category: "Para mamá", image: "images/wishlist/pantuflas.jpg", url: "https://www.mercadolibre.com.ar/pantuflas-mujer-invierno-peluche-polar-hasta-talle-4142/up/MLAU4111134927" },
  { id: "camisones", name: "Camisones de manga corta", category: "Para mamá", image: "images/wishlist/camisones.jpg", url: "https://articulo.mercadolibre.com.ar/MLA-1416027663-camison-maternal-_JM" },
  { id: "conjunto-mama", name: "Conjunto de camisa y short", category: "Para mamá", image: "images/wishlist/conjunto-mama.jpg", url: "https://www.xn--risueos-8za.com.ar/productos/pijama-maternal-mimbi-short-musculosa-para-amamantar-bata-beige/" },
  { id: "bata", name: "Bata", category: "Para mamá", image: "images/wishlist/bata.jpg", url: "https://www.mercadolibre.com.ar/bata-manga-largacamison-lactancia-con-top-amamantar/up/MLAU3905256347" },
  { id: "protectores", name: "Protectores mamarios descartables", category: "Para mamá", image: "images/wishlist/protectores.jpg", url: "https://listado.mercadolibre.com.ar/protectores-mamarios" },
  { id: "crema-calendula", name: "Crema de caléndula", category: "Para mamá", image: "images/wishlist/crema-calendula.jpg", url: "https://www.mercadolibre.com.ar/ewe-crema-de-calendula-60grs/up/MLAU189528609" },
  { id: "apositos", name: "Apósitos postparto", category: "Para mamá", image: "images/wishlist/apositos.jpg", url: "https://listado.mercadolibre.com.ar/apositos-postparto" },
  { id: "panales-postparto", name: "Bombachas postparto", category: "Para mamá", image: "images/wishlist/panales-postparto.jpg", url: "https://shop.aliceinmomland.com/productos/bombachas-postparto-plenitud/" },
];
